name: Keep Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping mcp-hub
        run: curl -f https://mcp-hub-cdnq.onrender.com/api/health || echo "Server javob bermadi"
